name: 'Geenii Action'
description: 'Runs a geenii agent'
author: 'fm-labs'

inputs:
  prompt:
    description: 'Override the default prompt'
    required: false
    default: ''
  model:
    description: 'Override the default model to use'
    required: false
    default: 'openai:gpt-4o-mini'

outputs:
  geenii-output:
    description: 'Output from the geenii agent'
  exit-code:
    description: 'Exit code'

runs:
  using: 'docker'
  image: 'fmlabs/geenii:latest'
  env:
    DEFAULT_COMPLETION_MODEL: ${{ inputs.model }}
    GEENII_DIR: '/github/workspace/.geenii'
    GEENII_USER_DIR: '/github/workspace/.geenii'
  args:
    - geenii
    - "${{ inputs.prompt }}"

branding:
  icon: 'shield'
  color: 'blue'